- company: Amazon
  platform: none
  custom: true
  slug:
  module: amazon
  url:

- company: Microsoft
  platform: none
  custom: true
  slug:
  module: microsoft
  url:

- company: Wealthsimple
  platform: none
  custom: true
  slug:
  module: wealthsimple
  url:

- company: Autodesk
  platform: workday
  custom: false
  slug:
  module: autodesk
  url:

- company: Capital One
  platform: workday
  custom: true
  slug:
  module: capital_one
  url:

- company: Nvidia
  platform: workday
  custom: true
  slug:
  module: nvidia
  url:

- company: Shopify
  platform: none
  custom: true
  slug:
  module: shopify
  url:

- company: Cisco
  platform: workday
  custom: true
  slug:
  module: cisco
  url:

- company: Morgan Stanley
  platform: workday
  custom: true
  slug:
  module: morgan_stanley
  url:

- company: Adobe
  platform: workday
  custom: true
  slug:
  module: adobe
  url:

- company: Stripe
  platform: none
  custom: true
  slug:
  module: stripe
  url:

- company: Intact
  platform: workday
  custom: false
  slug:
  module: intact
  url:

- company: Intel
  platform: workday
  custom: false
  slug:
  module: intel
  url:

- company: RBC
  platform: workday
  custom: true
  slug:
  module: rbc
  url:

- company: Warner Bros
  platform: workday
  custom:  true
  slug:
  module: warner_bros
  url: